services:
  # MariaDB database service
  ondine-db:
    image: mariadb:latest
    container_name: ondine-db
    hostname: ondine-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=DBManagerOndine2025  # Change in production
      - MYSQL_DATABASE=ondine
      - MYSQL_USER=ondine
      - MYSQL_PASSWORD=DBManagerOndine2025  # Change in production
    volumes:
      - ondine_data:/var/lib/mysql  # Data persistence
    ports:
      - "13306:3306"  # Port for external access (optional in prod)

  # PHP application service with Ondine
  ondine:
    build:
      context: ../  # Build from parent directory
      dockerfile: docker/Dockerfile
    container_name: ondine
    hostname: ondine
    restart: unless-stopped
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      # Database configuration
      - DB_DRIVER=mariadb
      - MYSQL_HOST=ondine-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ondine
      - MYSQL_USER=ondine
      - MYSQL_PASSWORD=DBManagerOndine2025  # Change in production
      # JWT Configuration
      - JWT_SECRET=your_secure_jwt_secret_change_in_production  # Change in production!
      # Seeds for initial user
      - SEED_PROFILE_NAME=Administrator
      - SEED_PROFILE_PERMISSIONS={"admin":1,"profiles":1,"users":1}
      - SEED_ADMIN_USERNAME=sysadmin  # Change in production
      - SEED_ADMIN_PASSWORD=SecureAdmin2025  # Change in production!
    # Uncommented for uploaded files
    #volumes:
    #  - ondine_files:/var/www/html/public
    depends_on:
      - ondine-db

  # Nginx service as reverse proxy and web server
  ondine-nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Nginx configuration
      - ../frontend/build:/var/www/html/public  # React frontend build
      - ../public/docs:/var/www/html/public/docs:ro  # API documentation
    container_name: ondine-nginx
    hostname: ondine-nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Web server port
    depends_on:
      - ondine

volumes:
  ondine_data:  # Volume for MariaDB data
  #ondine_files:  # Volume for uploaded files (uncomment if used)

networks:
  default:
    name: container-network
    external: true  # Shared external network